# -*- coding: utf-8 -*-
"""Checklist Pemeriksaan BIB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udM3266zqlR31AjMy1DGDHUmrVl5QYdv
"""

!pip install streamlit
!streamlit run app.py

import streamlit as st
import pandas as pd
from datetime import datetime

# Konfigurasi halaman
st.set_page_config(
    page_title="Checklist Pemeriksaan BIB",
    page_icon="✅",
    layout="centered"
)

# Custom CSS biar mirip Bootstrap
st.markdown("""
<style>
    .main-header {
        text-align: center;
        margin-bottom: 2rem;
    }
    .main-header h1 {
        color: #0d2550;
        font-weight: bold;
    }
    .main-header h6 {
        color: #6c757d;
    }
    .section-header {
        color: #0d2550;
        font-weight: bold;
        margin-top: 1.5rem;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #0d2550;
    }
    .kategori-card {
        background-color: #f8f9fa;
        padding: 1.5rem;
        border-radius: 10px;
        margin-bottom: 1.5rem;
    }
    .footer {
        text-align: center;
        color: #6c757d;
        margin-top: 3rem;
        padding: 1rem;
        background-color: #0d2550;
        color: white;
        border-radius: 5px;
    }
    .stRadio > div {
        display: flex;
        gap: 2rem;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.markdown('<div class="main-header"><h1>Checklist Pemeriksaan BIB</h1><h6>Astra Isuzu Waru</h6></div>', unsafe_allow_html=True)

# Inisialisasi session state untuk menyimpan data
if 'form_submitted' not in st.session_state:
    st.session_state.form_submitted = False
if 'hasil' not in st.session_state:
    st.session_state.hasil = None
if 'item_rusak' not in st.session_state:
    st.session_state.item_rusak = []

# FORM UTAMA
with st.form("form_checklist"):

    # A. Data Pemeriksaan
    st.markdown('<p class="section-header">A. Data Pemeriksaan</p>', unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        nama = st.text_input("Nama Pemeriksa", placeholder="Contoh: Budi")
    with col2:
        tanggal = st.date_input("Tanggal Pemeriksaan", value=datetime.now())

    st.markdown("---")

    # B. Kelengkapan Surat
    st.markdown('<p class="section-header">B. Kelengkapan Surat</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    stnk = st.radio(
        "1. STNK (Surat Tanda Nomor Kendaraan)",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="stnk"
    )

    sim = st.radio(
        "2. SIM Pengemudi",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="sim"
    )

    asuransi = st.radio(
        "3. Asuransi Kendaraan",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="asuransi"
    )

    surat_jalan = st.radio(
        "4. Surat Tugas/Surat Jalan",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="surat_jalan"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    # C. Perlengkapan Keselamatan
    st.markdown('<p class="section-header">C. Perlengkapan Keselamatan</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    ban_cadangan = st.radio(
        "1. Ban Cadangan",
        options=["Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="ban_cadangan"
    )

    kotak_p3k = st.radio(
        "2. Kotak P3K",
        options=["Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="kotak_p3k"
    )

    segitiga = st.radio(
        "3. Segitiga Pengaman",
        options=["Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="segitiga"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    # D. Kelengkapan BIB
    st.markdown('<p class="section-header">D. Kelengkapan BIB</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    oli = st.radio(
        "1. Oli Mesin",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="oli"
    )

    toolkit = st.radio(
        "2. Toolkit",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="toolkit"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    st.markdown("---")

    # Tombol Submit
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        submitted = st.form_submit_button("Kirim Hasil Pemeriksaan ✅", use_container_width=True)

# Handle setelah submit
if submitted:
    # Validasi semua field terisi
    semua_terisi = all([
        nama,
        stnk is not None,
        sim is not None,
        asuransi is not None,
        surat_jalan is not None,
        ban_cadangan is not None,
        kotak_p3k is not None,
        segitiga is not None,
        oli is not None,
        toolkit is not None
    ])

    if semua_terisi:
        # Hitung kelayakan
        total_item = 9  # total item yang dicek
        item_baik = 0
        item_rusak = []

        # Cek B. Kelengkapan Surat (4 item)
        if stnk == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("STNK")

        if sim == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("SIM")

        if asuransi == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Asuransi")

        if surat_jalan == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Surat Jalan")

        # Cek C. Perlengkapan Keselamatan (3 item)
        if ban_cadangan == "Ada":
            item_baik += 1
        else:
            item_rusak.append("Ban Cadangan")

        if kotak_p3k == "Ada":
            item_baik += 1
        else:
            item_rusak.append("Kotak P3K")

        if segitiga == "Ada":
            item_baik += 1
        else:
            item_rusak.append("Segitiga Pengaman")

        # Cek D. Kelengkapan BIB (2 item)
        if oli == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Oli Mesin")

        if toolkit == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Toolkit")

        # Simpan ke session state
        st.session_state.form_submitted = True
        st.session_state.item_baik = item_baik
        st.session_state.total_item = total_item
        st.session_state.item_rusak = item_rusak
        st.session_state.nama = nama
        st.session_state.tanggal = tanggal

        # Tampilkan hasil
        st.markdown("---")
        st.markdown('<p class="section-header">E. Hasil Pemeriksaan</p>', unsafe_allow_html=True)

        col_hasil = st.columns([1, 3, 1])
        with col_hasil[1]:
            if item_baik == total_item:
                st.success("## ✅ LAYAK JALAN")
                st.info("Semua komponen dalam kondisi baik. Kendaraan siap digunakan.")
            else:
                st.error("## ❌ TIDAK LAYAK JALAN")
                st.warning("Perlu perbaikan pada:")
                for item in item_rusak:
                    st.markdown(f"• {item}")

        # Tampilkan detail pemeriksaan
        with st.expander("Lihat Detail Pemeriksaan"):
            data_detail = {
                "Kategori": ["Kelengkapan Surat"]*4 + ["Keselamatan"]*3 + ["BIB"]*2,
                "Komponen": [
                    "STNK", "SIM", "Asuransi", "Surat Jalan",
                    "Ban Cadangan", "Kotak P3K", "Segitiga",
                    "Oli Mesin", "Toolkit"
                ],
                "Status": [
                    stnk, sim, asuransi, surat_jalan,
                    ban_cadangan, kotak_p3k, segitiga,
                    oli, toolkit
                ]
            }
            df = pd.DataFrame(data_detail)
            st.dataframe(df, use_container_width=True)

            st.write(f"**Nama Pemeriksa:** {nama}")
            st.write(f"**Tanggal:** {tanggal.strftime('%d %B %Y')}")

            # Tombol untuk reset
            if st.button("Periksa Lagi"):
                st.session_state.form_submitted = False
                st.rerun()

    else:
        st.warning("⚠️ Harap isi semua pertanyaan sebelum mengirim!")

# Footer
st.markdown('<div class="footer">&copy; Astra Isuzu Waru | Created at March 2026</div>', unsafe_allow_html=True)