# -*- coding: utf-8 -*-
"""Checklist Pemeriksaan BIB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udM3266zqlR31AjMy1DGDHUmrVl5QYdv
"""

import streamlit as st
import pandas as pd
import requests
from datetime import datetime

# Konfigurasi halaman
st.set_page_config(
    page_title="Checklist Pemeriksaan BIB",
    page_icon="✅",
    layout="centered"
)

# Custom CSS biar mirip Bootstrap
st.markdown("""
<style>
    .main-header {
        text-align: center;
        margin-bottom: 2rem;
    }
    .main-header h1 {
        color: #0d2550;
        font-weight: bold;
    }
    .main-header h6 {
        color: #6c757d;
    }
    .section-header {
        color: #0d2550;
        font-weight: bold;
        margin-top: 1.5rem;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #0d2550;
    }
    .kategori-card {
        background-color: #f8f9fa;
        padding: 1.5rem;
        border-radius: 10px;
        margin-bottom: 1.5rem;
    }
    .footer {
        text-align: center;
        color: #6c757d;
        margin-top: 3rem;
        padding: 1rem;
        background-color: #0d2550;
        color: white;
        border-radius: 5px;
    }
    .stRadio > div {
        display: flex;
        gap: 2rem;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.markdown('<div class="main-header"><h1>Checklist Pemeriksaan BIB</h1><h6>Astra Isuzu Waru</h6></div>', unsafe_allow_html=True)

# Inisialisasi session state untuk menyimpan data
if 'form_submitted' not in st.session_state:
    st.session_state.form_submitted = False
if 'hasil' not in st.session_state:
    st.session_state.hasil = None
if 'item_rusak' not in st.session_state:
    st.session_state.item_rusak = []

# FORM UTAMA
with st.form("form_checklist"):

    # A. Data Pemeriksaan
    st.markdown('<p class="section-header">A. Data Pemeriksaan</p>', unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        nama = st.text_input("Nama Pemeriksa", placeholder="Contoh: Budi")
    with col2:
        tanggal = st.date_input("Tanggal Pemeriksaan", value=datetime.now())

    st.markdown("---")

    # B. Kelengkapan Surat
    st.markdown('<p class="section-header">B. Kelengkapan Surat</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    stnk = st.radio(
        "1. STNK (Surat Tanda Nomor Kendaraan)",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="stnk"
    )

    sim = st.radio(
        "2. SIM Pengemudi",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="sim"
    )

    asuransi = st.radio(
        "3. Asuransi Kendaraan",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="asuransi"
    )

    surat_jalan = st.radio(
        "4. Surat Tugas/Surat Jalan",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="surat_jalan"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    # C. Perlengkapan Keselamatan
    st.markdown('<p class="section-header">C. Perlengkapan Keselamatan</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    ban_cadangan = st.radio(
        "1. Ban Cadangan",
        options=["Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="ban_cadangan"
    )

    kotak_p3k = st.radio(
        "2. Kotak P3K",
        options=["Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="kotak_p3k"
    )

    segitiga = st.radio(
        "3. Segitiga Pengaman",
        options=["Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="segitiga"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    # D. Kelengkapan BIB
    st.markdown('<p class="section-header">D. Kelengkapan BIB</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    oli = st.radio(
        "1. Oli Mesin",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="oli"
    )

    toolkit = st.radio(
        "2. Toolkit",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="toolkit"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    # E. Kondisi Mesin
    st.markdown('<p class="section-header">E. Kondisi Mesin</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    radiator = st.radio(
        "1. Air Radiator",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="radiator"
    )

    air_wiper = st.radio(
        "2. Air Wiper",
        options=["Ya, Ada", "Tidak Ada"],
        index=None,
        horizontal=True,
        key="air_wiper"
    )

    check_engine = st.radio(
        "3. Lampu Check Engine",
        options=["Mati", "Menyala"],
        index=None,
        horizontal=True,
        key="check_engine"
    )

    ac = st.radio(
        "4. AC/Pendingin Udara",
        options=["Berfungsi", "Tidak Berfungsi"],
        index=None,
        horizontal=True,
        key="ac"
    )

    pedal = st.radio(
        "5. Pedal gas, rem, dan kopling",
        options=["Responsif", "Tidak Responsif"],
        index=None,
        horizontal=True,
        key="pedal"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    # F. Kondisi Luar Kendaraan
    st.markdown('<p class="section-header">F. Kondisi Luar Kendaraan</p>', unsafe_allow_html=True)
    st.markdown('<div class="kategori-card">', unsafe_allow_html=True)

    lampu_depan = st.radio(
        "1. Lampu Depan",
        options=["Menyala", "Mati"],
        index=None,
        horizontal=True,
        key="lampu_depan"
    )

    lampu_kota = st.radio(
        "2. Lampu Kota",
        options=["Menyala", "Mati"],
        index=None,
        horizontal=True,
        key="lampu_kota"
    )

    lampu_rem = st.radio(
        "3. Lampu rem",
        options=["Menyala", "Mati"],
        index=None,
        horizontal=True,
        key="lampu_rem"
    )

    lampu_sein = st.radio(
        "4. Lampu Sein",
        options=["Menyala", "Mati"],
        index=None,
        horizontal=True,
        key="lampu_sein"
    )

    klakson = st.radio(
        "5. Klakson",
        options=["Berbunyi", "Tidak Berbunyi"],
        index=None,
        horizontal=True,
        key="klakson"
    )

    wiper = st.radio(
        "6. Wiper",
        options=["Berfungsi", "Tidak Berfungsi"],
        index=None,
        horizontal=True,
        key="wiper"
    )

    sabuk_pengaman = st.radio(
        "7. Kondisi Sabuk Pengaman",
        options=["Baik", "Rusak"],
        index=None,
        horizontal=True,
        key="sabuk_pengaman"
    )

    st.markdown('</div>', unsafe_allow_html=True)

    st.markdown("---")

    # Tombol Submit
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        submitted = st.form_submit_button("Kirim Hasil Pemeriksaan ✅", use_container_width=True)

# Handle setelah submit
if submitted:
    # Validasi semua field terisi
    semua_terisi = all([
        nama,
        stnk is not None,
        sim is not None,
        asuransi is not None,
        surat_jalan is not None,
        ban_cadangan is not None,
        kotak_p3k is not None,
        segitiga is not None,
        oli is not None,
        toolkit is not None,
        radiator is not None,
        air_wiper is not None,
        check_engine is not None,
        ac is not None,
        pedal is not None,
        lampu_depan is not None,
        lampu_kota is not None,
        lampu_rem is not None,
        lampu_sein is not None,
        klakson is not None,
        wiper is not None,
        sabuk_pengaman is not None
    ])

    if semua_terisi:
        # Hitung kelayakan
        total_item = 21
        item_baik = 0
        item_rusak = []

        # Cek B. Kelengkapan Surat
        if stnk == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("STNK")

        if sim == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("SIM")

        if asuransi == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Asuransi")

        if surat_jalan == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Surat Jalan")

        # Cek C. Perlengkapan Keselamatan (3 item)
        if ban_cadangan == "Ada":
            item_baik += 1
        else:
            item_rusak.append("Ban Cadangan")

        if kotak_p3k == "Ada":
            item_baik += 1
        else:
            item_rusak.append("Kotak P3K")

        if segitiga == "Ada":
            item_baik += 1
        else:
            item_rusak.append("Segitiga Pengaman")

        # Cek D. Kelengkapan BIB (2 item)
        if oli == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Oli Mesin")

        if toolkit == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Toolkit")

        # Cek E. Kondisi Mesin (5 item)
        if radiator == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Air Radiator")

        if air_wiper == "Ya, Ada":
            item_baik += 1
        else:
            item_rusak.append("Air Wiper")

        if check_engine == "Mati":
            item_baik += 1
        else:
            item_rusak.append("Lampu Check Engine")

        if ac == "Berfungsi":
            item_baik += 1
        else:
            item_rusak.append("AC/Pendingin Udara")

        if pedal == "Responsif":
            item_baik += 1
        else:
            item_rusak.append("Pedal Gas, Rem, dan Kopling")

        # Cek F. Kondisi Luar Kendaraan (7 item)
        if lampu_depan == "Menyala":
            item_baik += 1
        else:
            item_rusak.append("Lampu Depan")

        if lampu_kota == "Menyala":
            item_baik += 1
        else:
            item_rusak.append("Lampu Kota")

        if lampu_rem == "Menyala":
            item_baik += 1
        else:
            item_rusak.append("Lampu Rem")

        if lampu_sein == "Menyala":
            item_baik += 1
        else:
            item_rusak.append("Lampu Sein")

        if klakson == "Berbunyi":
            item_baik += 1
        else:
            item_rusak.append("Klakson")

        if wiper == "Berfungsi":
            item_baik += 1
        else:
            item_rusak.append("Wiper")

        if sabuk_pengaman == "Baik":
            item_baik += 1
        else:
            item_rusak.append("Sabuk Pengaman")

        # Simpan ke session state
        st.session_state.form_submitted = True
        st.session_state.item_baik = item_baik
        st.session_state.total_item = total_item
        st.session_state.item_rusak = item_rusak
        st.session_state.nama = nama
        st.session_state.tanggal = tanggal

        # Konfigurasi API Google Sheet
        url = "https://v1.nocodeapi.com/ranti123/google_sheets/YsShtvKdiSgBnXDb?tabId=Sheet1"
        params = {}
        data_kirim = [[
            datetime.now().strftime('%Y-%m-%d %H:%M:%S'),  # Timestamp
            nama,                                           # Nama Pemeriksa
            tanggal.strftime('%Y-%m-%d'),                   # Tanggal
            stnk,                                           # STNK
            sim,                                            # SIM
            asuransi,                                       # Asuransi
            surat_jalan,                                    # Surat Jalan
            ban_cadangan,                                   # Ban Cadangan
            kotak_p3k,                                      # Kotak P3K
            segitiga,                                       # Segitiga
            oli,                                            # Oli
            toolkit,                                        # Toolkit
            radiator,                                       # Radiator
            air_wiper,                                      # Air Wiper
            check_engine,                                   # Check Engine
            ac,                                             # AC
            pedal,                                          # Pedal
            lampu_depan,                                    # Lampu Depan
            lampu_kota,                                     # Lampu Kota
            lampu_rem,                                      # Lampu Rem
            lampu_sein,                                     # Lampu Sein
            klakson,                                        # Klakson
            wiper,                                          # Wiper
            sabuk_pengaman,                                 # Sabuk Pengaman
            'LAYAK JALAN' if item_baik == total_item else 'TIDAK LAYAK JALAN'  # Status
        ]]

        # Kirim data
        try:
            response = requests.post(url=url, params=params, json=data_kirim)

            # Cek response
            if response.status_code == 200:
                st.success("✅ Data berhasil disimpan ke Google Sheets!")

                with st.expander("Detail Response API"):
                    st.json(response.json())
            else:
                st.error(f"Gagal menyimpan: {response.status_code}")
                st.write(response.text)

        except Exception as e:
            st.error(f"Error koneksi: {e}")

        # Tampilkan hasil
        st.markdown("---")
        st.markdown('<p class="section-header">G. Hasil Pemeriksaan</p>', unsafe_allow_html=True)

        col_hasil = st.columns([1, 3, 1])
        with col_hasil[1]:
            if item_baik == total_item:
                st.success("## ✅ LAYAK JALAN")
                st.info("Semua komponen dalam kondisi baik. Kendaraan siap digunakan.")
            else:
                st.error("## ❌ TIDAK LAYAK JALAN")
                st.warning("Perlu perbaikan pada:")
                for item in item_rusak:
                    st.markdown(f"• {item}")

        # Tampilkan detail pemeriksaan
        with st.expander("Lihat Detail Pemeriksaan"):
            data_detail = {
                "Kategori": ["Kelengkapan Surat"]*4 + ["Keselamatan"]*3 + ["BIB"]*2 + ["Kondisi Mesin"]*5 + ["Kondisi Luar"]*7,
                "Komponen": [
                    "STNK", "SIM", "Asuransi", "Surat Jalan",
                    "Ban Cadangan", "Kotak P3K", "Segitiga",
                    "Oli Mesin", "Toolkit",
                    "Air Radiator", "Air Wiper", "Lampu Check Engine", "AC/Pendingin Udara", "Pedal Gas, Rem, dan Kopling",
                    "Lampu Depan", "Lampu Kota", "Lampu Rem", "Lampu Sein", "Klakson", "Wiper", "Kondisi Sabuk Pengaman"
                ],
                "Status": [
                    stnk, sim, asuransi, surat_jalan,
                    ban_cadangan, kotak_p3k, segitiga,
                    oli, toolkit,
                    radiator, air_wiper, check_engine, ac, pedal,
                    lampu_depan, lampu_kota, lampu_rem, lampu_sein, klakson, wiper, sabuk_pengaman
                ]
            }
            df = pd.DataFrame(data_detail)
            st.dataframe(df, use_container_width=True)

            st.write(f"**Nama Pemeriksa:** {nama}")
            st.write(f"**Tanggal:** {tanggal.strftime('%d %B %Y')}")

            # Tombol untuk reset
            if st.button("Periksa Lagi"):
                st.session_state.form_submitted = False
                st.rerun()

    else:
        st.warning("⚠️ Harap isi semua pertanyaan sebelum mengirim!")

# Footer
st.markdown('<div class="footer">&copy; Astra Isuzu Waru | Created at March 2026</div>', unsafe_allow_html=True)