# -*- coding: utf-8 -*-
"""pages/2_Riwayat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dfBT5MWZgiIZrR1iNy72u9fk5f4BSf2
"""

import streamlit as st
import pandas as pd
import requests
from datetime import datetime

# CSS
st.set_page_config(
    page_title="Riwayat Pemeriksaan BIB",
    page_icon="📊",
    layout="wide"
)

st.markdown("""
<style>
    .main-header {
        text-align: center;
        margin-bottom: 2rem;
    }
    .main-header h1 {
        color: #0d2550;
        font-weight: bold;
    }
    .main-header h6 {
        color: #6c757d;
    }
    .footer {
        text-align: center;
        color: #6c757d;
        margin-top: 3rem;
        padding: 1rem;
        background-color: #0d2550;
        color: white;
        border-radius: 5px;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.markdown('<div class="main-header"><h1>📋 Riwayat Pemeriksaan BIB</h1><h6>Astra Isuzu Waru</h6></div>', unsafe_allow_html=True)

# Konfigurasi API Google Sheet (SAMA PERSIS dengan di app.py)
url = "https://v1.nocodeapi.com/ranti123/google_sheets/YsShtvKdiSgBnXDb"
params = {"tabId": "Sheet1"}

try:
    # Ambil data dari Google Sheets (pakai method GET)
    response = requests.get(url, params=params)

    if response.status_code == 200:
        data = response.json()

        # Kalau ada data
        if data and len(data) > 0:
            # Konversi ke DataFrame
            df = pd.DataFrame(data[1:], columns=data[0])  # Baris 1 jadi header

            # Ubah kolom Timestamp ke datetime
            df['Timestamp'] = pd.to_datetime(df['Timestamp'])

            # --- SIDEBAR FILTER ---
            st.sidebar.header("🔍 Filter Data")

            # Filter Tanggal
            st.sidebar.subheader("Filter Tanggal")
            min_date = df['Timestamp'].dt.date.min()
            max_date = df['Timestamp'].dt.date.max()

            start_date = st.sidebar.date_input(
                "Dari Tanggal",
                value=min_date,
                min_value=min_date,
                max_value=max_date
            )

            end_date = st.sidebar.date_input(
                "Sampai Tanggal",
                value=max_date,
                min_value=min_date,
                max_value=max_date
            )

            # Filter Status
            st.sidebar.subheader("Filter Status")
            semua_status = ['Semua'] + sorted(df['Status'].unique().tolist())
            filter_status = st.sidebar.selectbox("Pilih Status", semua_status)

            # Filter Pemeriksa
            st.sidebar.subheader("Filter Pemeriksa")
            semua_pemeriksa = ['Semua'] + sorted(df['Nama Pemeriksa'].unique().tolist())
            filter_pemeriksa = st.sidebar.selectbox("Pilih Pemeriksa", semua_pemeriksa)

            # Tombol Reset Filter
            if st.sidebar.button("Reset Filter"):
                start_date = min_date
                end_date = max_date
                filter_status = 'Semua'
                filter_pemeriksa = 'Semua'
                st.rerun()

            # --- TERAPKAN FILTER ---
            df_filtered = df.copy()

            # Filter tanggal
            mask_tanggal = (df_filtered['Timestamp'].dt.date >= start_date) & (df_filtered['Timestamp'].dt.date <= end_date)
            df_filtered = df_filtered[mask_tanggal]

            # Filter status
            if filter_status != 'Semua':
                df_filtered = df_filtered[df_filtered['Status'] == filter_status]

            # Filter pemeriksa
            if filter_pemeriksa != 'Semua':
                df_filtered = df_filtered[df_filtered['Nama Pemeriksa'] == filter_pemeriksa]

            # --- METRIKS RINGKASAN ---
            st.markdown("## 📊 Ringkasan Data")
            col1, col2, col3, col4, col5 = st.columns(5)

            with col1:
                st.metric("Total Pemeriksaan", len(df_filtered))

            with col2:
                laik = len(df_filtered[df_filtered['Status'] == 'LAYAK JALAN'])
                st.metric("✅ LAYAK JALAN", laik)

            with col3:
                tidak_laik = len(df_filtered[df_filtered['Status'] == 'TIDAK LAYAK JALAN'])
                st.metric("❌ TIDAK LAYAK", tidak_laik)

            with col4:
                if len(df_filtered) > 0:
                    persen_laik = (laik / len(df_filtered)) * 100
                    st.metric("🎯 Persentase Laik", f"{persen_laik:.1f}%")

            with col5:
                periode = f"{start_date.strftime('%d/%m')} - {end_date.strftime('%d/%m')}"
                st.metric("📅 Periode", periode)

            st.markdown("---")

            # --- TABEL DATA ---
            st.markdown(f"## 📋 Detail Pemeriksaan ({len(df_filtered)} data)")

            # Tampilkan dataframe
            st.dataframe(
                df_filtered,
                use_container_width=True,
                hide_index=True,
                column_config={
                    "Timestamp": "Waktu Input",
                    "Nama Pemeriksa": "Pemeriksa",
                    "Tanggal": "Tgl Periksa",
                    "Status": st.column_config.Column(
                        "Status",
                        width="small",
                        pinned=True
                    )
                }
            )

            # --- DOWNLOAD DATA ---
            st.markdown("---")
            st.markdown("## 📥 Download Data")

            col1, col2 = st.columns(2)

            with col1:
                # Download data terfilter
                csv_filtered = df_filtered.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="📥 Download Data Terfilter (CSV)",
                    data=csv_filtered,
                    file_name=f"pemeriksaan_bib_filtered_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                    mime="text/csv",
                    use_container_width=True
                )

            with col2:
                # Download semua data
                csv_all = df.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="📥 Download Semua Data (CSV)",
                    data=csv_all,
                    file_name=f"pemeriksaan_bib_all_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                    mime="text/csv",
                    use_container_width=True
                )

            # --- GRAFIK SEDERHANA ---
            with st.expander("📈 Lihat Grafik"):
                col1, col2 = st.columns(2)

                with col1:
                    st.subheader("Status Pemeriksaan")
                    status_counts = df_filtered['Status'].value_counts()
                    st.bar_chart(status_counts)

                with col2:
                    st.subheader("Pemeriksaan per Hari")
                    df_filtered['Tanggal_short'] = df_filtered['Timestamp'].dt.date
                    per_hari = df_filtered.groupby('Tanggal_short').size()
                    st.line_chart(per_hari)

        else:
            st.info("📭 Belum ada data pemeriksaan. Silakan isi form terlebih dahulu.")
            # Tombol ke halaman form
            if st.button("+ Buat Pemeriksaan Baru"):
                st.switch_page("app.py")

    else:
        st.error(f"Gagal mengambil data: {response.status_code}")

except Exception as e:
    st.error(f"Error: {e}")

# Footer
st.markdown('<div class="footer">&copy; Astra Isuzu Waru | Created at March 2026</div>', unsafe_allow_html=True)